services:

  backend:
    container_name: e-commerce-express-container
    build: .
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    depends_on:
      - redis
      - mongo
  redis:
    image: redis
  
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: J3x123678
 
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: test
      ME_CONFIG_MONGODB_ADMINPASSWORD: J3x123678
      ME_CONFIG_MONGODB_URL: mongodb://test:J3x123678@mongo:27017/
      ME_CONFIG_BASICAUTH: false 
    depends_on:
      - mongo  
 

volumes:
  mongo-db:
