services:
  backend:
    build:
      context: .
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src:ro
    command: npm run start
