export enum ErrorCodes {
  BAD_REQUEST = "BAD_REQUEST",
  NOT_FOUND = "NOT_FOUND",
  INTERNAL_ERROR = "INTERNAL_ERROR",
  INVALID_CREDINTIALS = "INVALID_CREDINTIALS ",
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  USER_NOT_VERIFIED = "USER_NOT_VERIFIED",
  NO_REASON_TO_RESEND_CODE = "NO_REASON_TO_RESEND_CODE",
  UNAUTHENTICATED = "UNAUTHENTICATED",
  UNAUTHORIZED = "UNAUTHORIZED",
  INVALID_TOKEN = "INVALID_TOKEN",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  INVALID_VERIFICATION_CODE = "INVALID_VERIFICATION_CODE",
  CATEGORY_ALREADY_EXISTS = "CATEGORY_ALREADY_EXISTS",
  CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND",
  CATEGORY_HAS_CHILDREN = "CATEGORY_HAS_CHILDREN",
  INVALID_FILE_FORMAT = "INVALID_FILE_FORMAT",
}

export const ErrorMessages: Record<ErrorCodes, string> = {
  [ErrorCodes.BAD_REQUEST]: "Bad Request",
  [ErrorCodes.NOT_FOUND]: "Not Found",
  [ErrorCodes.INTERNAL_ERROR]: "Internal Server Error",
  [ErrorCodes.INVALID_CREDINTIALS]: "Invalid Credintials",
  [ErrorCodes.EMAIL_ALREADY_EXISTS]: "Email Already Exists",
  [ErrorCodes.USER_NOT_VERIFIED]: "User Not Verified",
  [ErrorCodes.NO_REASON_TO_RESEND_CODE]: "No Reason To Resend Code",
  [ErrorCodes.UNAUTHENTICATED]: "Unauthenticated",
  [ErrorCodes.UNAUTHORIZED]: "Unauthorized",
  [ErrorCodes.INVALID_TOKEN]: "Invalid Token",
  [ErrorCodes.VALIDATION_ERROR]: "Validation Error",
  [ErrorCodes.INVALID_VERIFICATION_CODE]: "Invalid Verification Code",
  [ErrorCodes.CATEGORY_ALREADY_EXISTS]: "Category Already Exists",
  [ErrorCodes.CATEGORY_NOT_FOUND]: "Category Not Found",
  [ErrorCodes.CATEGORY_HAS_CHILDREN]: "Category Has Children",
  [ErrorCodes.INVALID_FILE_FORMAT]: "Invalid File Format",
};
